# .pre-commit-config.yaml
repos:
  - repo: local
    hooks:
      - id: gofmt
        name: go fmt
        entry: hooks/pre-commit-gofmt
        language: script
        pass_filenames: false
      - id: gomarkdoc
        name: Generate Go Documentation
        entry: hooks/pre-commit-gomarkdoc
        language: script
        pass_filenames: false
